version: "3"

services:
  bare: &app
    image: node:16
    command: bash
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment:
      ENVIRONMENT_NAME: dev
      USE_SWAGGER_VALIDATION: ${USE_SWAGGER_VALIDATION:-"false"}
      INLINE_RUNTIME_CHUNK: "false"
  web:
    <<: *app
    ports:
      - 3000:3000
    command: yarn start

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
