format_version: 2
common:
  tasks:
    deploy: &deploy
      script: |
        set -e

        helm upgrade --install --wait --timeout 300s \
          --namespace ${PROJECT}-$K8S_NAMESPACE \
          ${CHART_NAME}-$K8S_NAMESPACE \
          ./chart/${CHART_NAME}-*.tgz \
          --values ./chart/${K8S_NAMESPACE}.yaml

pipelines:
  snacker-tracker-ui-test:
    group: snacker-tracker-ui
    label_template: "${git-snacker-tracker-ui[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? */15"
      only_on_changes: yes
    materials:
      git-snacker-tracker-ui:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/ui.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      #REGISTRY: "DEFINED ON THE AGENT"
      IMAGE: snacker-tracker/ui
      CHART_NAME: snacker-tracker-ui
      PROJECT: snacker-tracker
      GO_AUTOMATION_USER: automaton
      GITHUB_AUTOMATION_USER: gocd-service-account
    secure_variables:
      GO_AUTOMATION_PASSWORD: "AES:+heX4S6WsUXSqPxj5nNOoQ==:9jXtfK+GoUYDpS7mvGGWmA=="
      GITHUB_AUTOMATION_PASSWORD: "AES:EwOyEBf7z5d8VzVua75pEg==:LZhYZmLP7OR2Vf+NwirNlTCYCmptgbSRRqD3kWjjYlXxxCeSZGYyX07ZIcgMpfhV"
    stages:
      - tests:
          jobs:
            audit:
              tasks:
                - script: |
                    bash auto/push-commit-status \
                      snacker-tracker/ui \
                      ${GO_SCM_GIT_SNACKER_TRACKER_UI_LABEL} \
                      "pending" "Build is running"

                - script: |
                    ./auto/clean-up || true
                - script: |
                    function finish {
                      EXIT_CODE=$?
                      set +e

                      docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount

                      ./auto/clean-up || true

                       [[ $EXIT_CODE = 0 ]] && GH_STATUS="success" || GH_STATUS="failure"

                      bash auto/push-commit-status \
                        snacker-tracker/ui \
                        ${GO_SCM_GIT_SNACKER_TRACKER_UI_LABEL} \
                        $GH_STATUS "${GH_STATUS_DESCRIPTION}"

                      exit $EXIT_CODE
                    }

                    trap finish EXIT

                    AUDIT_RESULT="$(docker run -v `pwd`:/app/ -w /app/ node:10 yarn audit --json --groups dependencies --level moderate)"
                    export EXIT_CODE=$?

                    set -e

                    echo "$AUDIT_RESULT" | jq .

                    DEPENDENCIES="$(echo "$AUDIT_RESULT" | jq .data.dependencies)"
                    LOW="$(echo "$AUDIT_RESULT" | jq .data.vulnerabilities.low)"
                    MODERATE="$(echo "$AUDIT_RESULT" | jq .data.vulnerabilities.moderate)"
                    HIGH="$(echo "$AUDIT_RESULT" | jq .data.vulnerabilities.high)"
                    CRITICAL="$(echo "$AUDIT_RESULT" | jq .data.vulnerabilities.critical)"

                    export GH_STATUS_DESCRIPTION="$DEPENDENCIES dependencies - Low=$LOW Moderate=$MODERATE High=$HIGH Critical=$CRITICAL"

                    echo "$GH_STATUS_DESCRIPTION"

                    exit $EXIT_CODE

  snacker-tracker-ui-build:
    group: snacker-tracker-ui
    label_template: "0.1.${COUNT}-${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-ui-test
        stage: tests
      git-snacker-tracker-ui:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/ui.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      #REGISTRY: "DEFINED ON THE AGENT"
      IMAGE: snacker-tracker/ui
      CHART_NAME: snacker-tracker-ui
      PROJECT: snacker-tracker
    stages:
      - package:
          jobs:
            build-image:
              tasks:
                - script: |
                    set -e

                    ./auto/build

                    docker run -v `pwd`:/app/ alpine chown -R $(id -u):$(id -g) /app/build

                    docker build -t ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} \
                      --label version=${GO_PIPELINE_LABEL} \
                      --label git-commit=${GO_REVISION_GIT} \
                      --label go-pipeline=${GO_PIPELINE_NAME} \
                      --label go-pipeline-counter=${GO_PIPELINE_COUNTER} \
                      --label go-pipeline-stage=${GO_STAGE_NAME} \
                      --label go-pipeline-stage-counter=${GO_STAGE_COUNTER} \
                      --label go-pipeline-job=${GO_JOB_NAME} \
                      --build-arg APP_VERSION=${GO_PIPELINE_LABEL} \
                      .

                    docker tag ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} ${REGISTRY}/${IMAGE}:latest
                    docker push ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL}
                    docker push ${REGISTRY}/${IMAGE}:latest

            package:
              tasks:
                - script: |
                    set -e

                    helm lint helm-charts/${CHART_NAME}

                    helm package --version "$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')" --app-version $GO_PIPELINE_LABEL ./helm-charts/${CHART_NAME}
              artifacts:
                - build:
                    source: snacker-tracker-ui-*.tgz
                    destination: ./chart/
                - build:
                    source: helm-charts/values/*
                    destination: ./chart/

  snacker-tracker-ui-deploy-qa:
    group: snacker-tracker-ui
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-ui-build
        stage: package
    environment_variables:
      K8S_NAMESPACE: qa
      CHART_NAME: snacker-tracker-ui
      PROJECT: snacker-tracker
    stages:
      - deploy:
          jobs:
            helm-upgrade:
              tasks:
                - fetch:
                    pipeline: snacker-tracker-ui-build
                    stage: package
                    job: package
                    source: chart/
                    destination: ./
                - *deploy

  snacker-tracker-ui-deploy-prod:
    group: snacker-tracker-ui
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-ui-deploy-qa
        stage: deploy
    environment_variables:
      K8S_NAMESPACE: prod
      CHART_NAME: snacker-tracker-ui
      PROJECT: snacker-tracker
    stages:
      - deploy:
          jobs:
            helm-upgrade:
              tasks:
                - fetch:
                    pipeline: snacker-tracker-ui-build/snacker-tracker-ui-deploy-qa
                    stage: package
                    job: package
                    source: chart/
                    destination: ./
                - *deploy
