ingress:
  enabled: true
  hosts:
    - host: ui.snacker-tracker.prod.k8s.fscker.org
      paths:
        - /
  tls:
    - secretName: ui-snacker-tracker-prod-k8s-fscker-org
      hosts:
        - ui.snacker-tracker.prod.k8s.fscker.org

resources:
  # NON-DEFAULT: We should *always* specify `requests`, but probably not `limits`
  requests:
    cpu: 0.01
    memory: 16Mi

config:
  env:
    OAUTH_CLIENT_ID: Jn7nzWMOdZ1BZC4WhoIrvHk4bey46eUl
    OAUTH_ISSUER: fscker-public.eu.auth0.com
    OAUTH_AUDIENCE: snacker-tracker-reporter
    REPORTER_URL: https://reporter.snacker-tracker.prod.k8s.fscker.org/v1
