apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snacker-tracker-ui.fullname" . }}
  labels:
    {{- include "snacker-tracker-ui.labels" . | nindent 4 }}
data:
  config.js: |
    const CONFIG = {{ toJson .Values.config.env | indent 4 }}
